default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  username: 
  password: 

development:
  <<: *default
  database: rungazella_development
  username:
  password: 

test:
  <<: *default
  database: rungazella_test

production:
  <<: *default
  host: 
  database: rungazella
  username: rungazella
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>