default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: rungazella_development
  password: 

test:
  <<: *default
  database: rungazella_test

production:
  <<: *default
  host: 
  database: app_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>