require 'rubygems'
require 'sitemap_generator'

SitemapGenerator::Sitemap.default_host = 'http://rungazella.com'
SitemapGenerator::Sitemap.create do
  	add '/home', :changefreq => 'daily', :priority => 0.9
  	add '/#products', :changefreq => 'weekly'
  	add '/products', :changefreq => 'weekly'
  	add '/products/alice-in-wonderland-inspired-running-costume', :changefreq => 'weekly'
  	add '/products/mrs-incredible-inspired-running-costume', :changefreq => 'weekly'
  	add '/products/wonderwoman-inspired-running-costume', :changefreq => 'weekly'
  	add '/products/alice-in-wonderland-inspired-race-legs', :changefreq => 'weekly'
  	add '/products/mrs-incredible-inspired-race-legs', :changefreq => 'weekly'
  	add '/products/wonder-woman-inspired-race-legs', :changefreq => 'weekly'
  	add '/products/mrs-incredible-inspired-running-singlet', :changefreq => 'weekly'
  	add '/products/mrs-incredible-inspired-running-skirt', :changefreq => 'weekly'
  	add '/products/wonder-woman-inspired-running-shorts', :changefreq => 'weekly'
  	add '/products/wonder-woman-inspired-running-singlet', :changefreq => 'weekly'
  	add '/products/wonder-woman-inspired-sweatband-tiara', :changefreq => 'weekly'
  	add '/t/running-costumes', :changefreq => 'weekly'
  	add '/t/wonder-woman', :changefreq => 'weekly'
  	add '/t/packages', :changefreq => 'weekly'
  	add '/t/mrs-incredible', :changefreq => 'weekly'
  	add '/t/individual-pieces', :changefreq => 'weekly'
  	add '/t/race-legs', :changefreq => 'weekly'
  	add '/t/alice-in-wonderland', :changefreq => 'weekly'
  	add '/blog', :changefreq => 'daily'
  	add '/our-story', :changefreq => 'weekly'
  	add '/content/size-guide', :changefreq => 'weekly'
	add '/content/shipping-taxes', :changefreq => 'weekly'
	add '/content/privacy-policy', :changefreq => 'weekly'
	add '/content/terms-conditions', :changefreq => 'weekly'
end
SitemapGenerator::Sitemap.ping_search_engines # Not needed if you use the rake tasks